In [23]:
import torch
x = torch.ones(2,2,requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [24]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [25]:
y.grad_fn

In [26]:
z = y * y * 3

In [27]:
out = z.mean()

In [28]:
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [29]:
a = torch.randn(2,2)

In [30]:
a = ((a*3)/(a-1))

In [31]:
print(a.requires_grad)

False


In [32]:
a.requires_grad_(True)

tensor([[  0.8837,  46.3164],
        [  1.5150, -18.4735]], requires_grad=True)

In [33]:
a

tensor([[  0.8837,  46.3164],
        [  1.5150, -18.4735]], requires_grad=True)

In [34]:
print(a.requires_grad)

True


In [35]:
b = (a*a).sum()

In [36]:
print(b.grad_fn)

In [38]:
print(x.grad)

None


In [39]:
x = torch.tensor(3.0,requires_grad = True)

In [40]:
y = torch.pow(x,2)

In [43]:
print(x.requires_grad)

True


In [45]:
print(y.requires_grad)

True


In [46]:
y.backward()

In [47]:
print(x.grad)

tensor(6.)


In [54]:
#创建一个二元函数，即z=f(x,y)=x2+y2，x可求导，y设置不可求导
x=torch.tensor(3.0,requires_grad=True)
y=torch.tensor(4.0,requires_grad=False)
z=torch.pow(x,2)+torch.pow(y,2)
 
#判断x,y是否是可以求导的
print(x.requires_grad)
print(y.requires_grad)
print(z.requires_grad)
 
#求导，通过backward函数来实现
z.backward()  
 
#查看导数，也即所谓的梯度
print(x.grad)
print(y.grad)
 
'''运行结果为：
True       # x是可导的
False      # y是不可导的
True       # z是可导的，因为它有一个 leaf variable 是可导的，即x可导
tensor(6.) # x的导数
None       # 因为y不可导，所以是none
'''

True
False
True
tensor(6.)
None


'运行结果为：\nTrue       # x是可导的\nFalse      # y是不可导的\nTrue       # z是可导的，因为它有一个 leaf variable 是可导的，即x可导\ntensor(6.) # x的导数\nNone       # 因为y不可导，所以是none\n'

In [64]:
import torch
x = torch.ones(2, 2, requires_grad=True)
print(x)
"""
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
"""
y = x + 2
print(y)
"""
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
"""
print(y.grad_fn)
"""
<AddBackward0 object at 0x7fc6bd199ac8>
"""
z = y * y * 3
out = z.mean()
print(z, out)
"""
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)
"""
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)
"""
False
True
<SumBackward0 object at 0x7fc6bd1b02e8>
"""


tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)
False
True


'\nFalse\nTrue\n<SumBackward0 object at 0x7fc6bd1b02e8>\n'

In [65]:
print(x.grad)
"""
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
"""


None


'\ntensor([[4.5000, 4.5000],\n        [4.5000, 4.5000]])\n'

In [66]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)
"""
tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])
"""
#停止计算微分
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
   print((x ** 2).requires_grad)
"""
True
True
False
"""


RuntimeError: Mismatch in shape: grad_output[0] has a shape of torch.Size([3]) and output[0] has a shape of torch.Size([2, 2]).

In [84]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([  213.7798, -1005.2238,  -532.0457], grad_fn=<MulBackward0>)


In [85]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([2.0480e+02, 2.0480e+03, 2.0480e-01])


In [86]:
y

tensor([  213.7798, -1005.2238,  -532.0457], grad_fn=<MulBackward0>)

In [87]:
v

tensor([1.0000e-01, 1.0000e+00, 1.0000e-04])

In [88]:
y.backward()

RuntimeError: grad can be implicitly created only for scalar outputs

In [72]:
x

tensor([-0.1038, -0.8907, -1.4499], requires_grad=True)

In [74]:
2*x

tensor([-0.2076, -1.7813, -2.8999], grad_fn=<MulBackward0>)

In [100]:
x = torch.ones(4,3,requires_grad=True)

In [101]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)

In [102]:
y = torch.pow(x,2)

In [105]:
x=torch.tensor(3.0,requires_grad=True)
y=torch.pow(x,2)
 
#判断x,y是否是可以求导的
print(x.requires_grad)
print(y.requires_grad)
 
#求导，通过backward函数来实现
y.backward()  
 
#查看导数，也即所谓的梯度
print(x.grad)

True
True
tensor(6.)


In [106]:
#创建一个二元函数，即z=f(x,y)=x2+y2，x可求导，y设置不可求导
x=torch.tensor(3.0,requires_grad=True)
y=torch.tensor(4.0,requires_grad=False)
z=torch.pow(x,2)+torch.pow(y,2)
 
#判断x,y是否是可以求导的
print(x.requires_grad)
print(y.requires_grad)
print(z.requires_grad)
 
#求导，通过backward函数来实现
z.backward()  
 
#查看导数，也即所谓的梯度
print(x.grad)
print(y.grad)
 
'''运行结果为：
True       # x是可导的
False      # y是不可导的
True       # z是可导的，因为它有一个 leaf variable 是可导的，即x可导
tensor(6.) # x的导数
None       # 因为y不可导，所以是none
'''

True
False
True
tensor(6.)
None


'运行结果为：\nTrue       # x是可导的\nFalse      # y是不可导的\nTrue       # z是可导的，因为它有一个 leaf variable 是可导的，即x可导\ntensor(6.) # x的导数\nNone       # 因为y不可导，所以是none\n'

In [107]:
x.grad

tensor(6.)

In [108]:
x

tensor(3., requires_grad=True)

In [109]:
y

tensor(4.)

In [110]:
z

tensor(25., grad_fn=<AddBackward0>)

In [136]:
#创建一个多元函数，即Y=XW+b=Y=x1*w1+x2*w2*x3*w3+b，x不可求导，W,b设置可求导
X=torch.tensor([1.5,2.5,3.5],requires_grad=False)
W=torch.tensor([0.2,0.4,0.6],requires_grad=True)
b=torch.tensor(0.1,requires_grad=True)
Y=torch.add(torch.dot(X,W),b)
 
    
#判断每个tensor是否是可以求导的
print(X.requires_grad)
print(W.requires_grad)
print(b.requires_grad)
print(Y.requires_grad)
 
 
#求导，通过backward函数来实现
Y.backward()  
 
#查看导数，也即所谓的梯度
print(W.grad)
print(b.grad)
 
'''运行结果为：
False
True
True
True
tensor([1.5000, 2.5000, 3.5000])
tensor(1.)
'''

False
True
True
True
tensor([1.5000, 2.5000, 3.5000])
tensor(1.)


'运行结果为：\nFalse\nTrue\nTrue\nTrue\ntensor([1.5000, 2.5000, 3.5000])\ntensor(1.)\n'

In [162]:
'''
x 是一个（2,3）的矩阵，设置为可导，是叶节点，即leaf variable
y 是中间变量,由于x可导，所以y可导
z 是中间变量,由于x，y可导，所以z可导
f 是一个求和函数，最终得到的是一个标量scaler
'''
 
x = torch.tensor([[1.,2.,3.],[4.,5.,6.]],requires_grad=True)
y = torch.tensor(torch.add(x,1),requires_grad=True)
z = 2*torch.pow(y,2)
f = torch.mean(z) 

/home/lpc/anaconda3/envs/gluon/lib/python3.6/site-packages/ipykernel_launcher.py:9: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  if __name__ == '__main__':


In [163]:
print(x.requires_grad)
print(y.requires_grad)
print(z.requires_grad)
print(f.requires_grad)
print('===================================')
f.backward(retain_graph=True)
# print(x.grad)
print(y.grad)


True
True
True
True
tensor([[1.3333, 2.0000, 2.6667],
        [3.3333, 4.0000, 4.6667]])


In [150]:
'''
x 是一个（2,3）的矩阵，设置为可导，是叶节点，即leaf variable
y 也是一个（2,3）的矩阵，即
y=x2+x (x的平方加x)
实际上，就是要y的各个元素对相对应的x求导
'''
 
x = torch.tensor([[1.,2.,3.],[4.,5.,6.]],requires_grad=True)
y = torch.add(torch.pow(x,2),x)
 
gradient=torch.tensor([[1.0,1.0,1.0],[1.0,1.0,1.0]])
 
y.backward(gradient)
 
print(x.grad)
 
'''运行结果为：
tensor([[ 3.,  5.,  7.],
        [ 9., 11., 13.]])
'''

tensor([[ 3.,  5.,  7.],
        [ 9., 11., 13.]])


'运行结果为：\ntensor([[ 3.,  5.,  7.],\n        [ 9., 11., 13.]])\n'

In [149]:
x = torch.tensor([1.,2.,3.],requires_grad=True)
y = torch.pow(x,2)
 
gradient=torch.tensor([1.0,1.0,1.0])
y.backward(gradient)
print(x.grad)
'''得到的结果：
tensor([2., 4., 6.])   这和我们期望的是一样的
'''  

tensor([2., 4., 6.])


'得到的结果：\ntensor([2., 4., 6.])   这和我们期望的是一样的\n'

In [209]:
x = torch.randn(3, requires_grad=True)

y = x * 2

while y.data.norm() < 1000:
    print(y.data.norm())
    y = y * 2
print(y)

tensor(3.0849)
tensor(6.1697)
tensor(12.3394)
tensor(24.6788)
tensor(49.3576)
tensor(98.7153)
tensor(197.4305)
tensor(394.8610)
tensor(789.7220)
tensor([   95.2732, -1518.5526,   423.7509], grad_fn=<MulBackward0>)


In [210]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)


tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [211]:
x

tensor([ 0.0930, -1.4830,  0.4138], requires_grad=True)

In [195]:
y.data.norm()

tensor(1880.3503)

In [184]:
x * 2

tensor([0.0731, 3.5209, 2.5828], grad_fn=<MulBackward0>)

In [185]:
x 

tensor([0.0366, 1.7604, 1.2914], requires_grad=True)

In [186]:
x 

tensor([0.0366, 1.7604, 1.2914], requires_grad=True)

In [187]:
x *2 *2 

tensor([0.1462, 7.0417, 5.1656], grad_fn=<MulBackward0>)