In [1]:
import torch

In [2]:
x = torch.empty(5,3)

In [3]:
x

tensor([[ 3.6091e-13,  4.5768e-41, -5.6650e-13],
        [ 3.0666e-41,         nan,  0.0000e+00],
        [ 7.6194e+31,  1.5564e+28,  4.7984e+30],
        [ 6.2121e+22,  1.8370e+25,  1.4603e-19],
        [ 1.6795e+08,  4.7423e+30,  4.7393e+30]])

In [4]:
print(x)

tensor([[ 3.6091e-13,  4.5768e-41, -5.6650e-13],
        [ 3.0666e-41,         nan,  0.0000e+00],
        [ 7.6194e+31,  1.5564e+28,  4.7984e+30],
        [ 6.2121e+22,  1.8370e+25,  1.4603e-19],
        [ 1.6795e+08,  4.7423e+30,  4.7393e+30]])


In [5]:
#生成一个均匀分布的初始化的 每个元素从0-1的张良。
x = torch.rand(5,3)

In [6]:
x

tensor([[0.1412, 0.0866, 0.0685],
        [0.9781, 0.1584, 0.0908],
        [0.7473, 0.6790, 0.9851],
        [0.6312, 0.7489, 0.3896],
        [0.8803, 0.6856, 0.9616]])

In [7]:
x = torch.randn(5,3)

In [8]:
x

tensor([[ 0.9731,  1.1318, -0.7469],
        [ 0.9416,  0.8847, -1.0151],
        [ 0.2489,  0.2659, -0.2523],
        [ 0.2151,  0.5830, -0.0403],
        [-1.7950, -0.0349, -1.3405]])

In [9]:
x = torch.tensor([5.5,3])
y = torch.rand(1,2)

In [10]:
x = x.new_ones(5,3,dtype = torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [11]:
x = torch.randn_like(x,dtype = torch.float)
print(x)

tensor([[-0.0283, -0.1408,  0.2278],
        [-0.6246, -0.6715, -1.6543],
        [ 0.0636, -0.3734, -0.6476],
        [ 0.7349,  0.0785,  0.3376],
        [-0.1963, -0.6158, -0.4567]])


In [12]:
print(x.size())

torch.Size([5, 3])


In [13]:
y = torch.rand(5,3)

In [14]:
print(x +y )

tensor([[ 4.8928e-01,  7.6159e-02,  3.8588e-01],
        [-4.0087e-01, -2.0074e-01, -7.9421e-01],
        [ 2.3357e-01,  3.4588e-01, -4.4539e-01],
        [ 1.6271e+00,  5.5308e-01,  1.1336e+00],
        [-1.4273e-03, -2.7928e-01, -2.5047e-01]])


In [15]:
print(y.add(x))

tensor([[ 4.8928e-01,  7.6159e-02,  3.8588e-01],
        [-4.0087e-01, -2.0074e-01, -7.9421e-01],
        [ 2.3357e-01,  3.4588e-01, -4.4539e-01],
        [ 1.6271e+00,  5.5308e-01,  1.1336e+00],
        [-1.4273e-03, -2.7928e-01, -2.5047e-01]])


In [16]:
result = torch.empty(5,3)
torch.add(x,y,out = result)
print(result)

tensor([[ 4.8928e-01,  7.6159e-02,  3.8588e-01],
        [-4.0087e-01, -2.0074e-01, -7.9421e-01],
        [ 2.3357e-01,  3.4588e-01, -4.4539e-01],
        [ 1.6271e+00,  5.5308e-01,  1.1336e+00],
        [-1.4273e-03, -2.7928e-01, -2.5047e-01]])


In [17]:
x[:,1]

tensor([-0.1408, -0.6715, -0.3734,  0.0785, -0.6158])

In [18]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [19]:
x

tensor([[ 0.5352,  0.8761,  0.3468,  1.2977],
        [ 0.6653,  0.9737, -0.2880,  0.5690],
        [ 0.9584, -0.1313,  0.2494,  0.3314],
        [ 1.0418,  1.3972,  0.8570,  0.3844]])

In [20]:
y

tensor([ 0.5352,  0.8761,  0.3468,  1.2977,  0.6653,  0.9737, -0.2880,  0.5690,
         0.9584, -0.1313,  0.2494,  0.3314,  1.0418,  1.3972,  0.8570,  0.3844])

In [21]:
z

tensor([[ 0.5352,  0.8761,  0.3468,  1.2977,  0.6653,  0.9737, -0.2880,  0.5690],
        [ 0.9584, -0.1313,  0.2494,  0.3314,  1.0418,  1.3972,  0.8570,  0.3844]])

In [22]:
x = x.view(2,8)

In [23]:
x

tensor([[ 0.5352,  0.8761,  0.3468,  1.2977,  0.6653,  0.9737, -0.2880,  0.5690],
        [ 0.9584, -0.1313,  0.2494,  0.3314,  1.0418,  1.3972,  0.8570,  0.3844]])

In [24]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [25]:
b = a.numpy()

In [26]:
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [27]:
torch.is_tensor(b)

False

In [28]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [41]:
import time
if torch.cuda.is_available():
    device = torch.device("cuda")          
    y = torch.ones_like(x, device=device)  
    x = x.to(device)   
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       


tensor([[ 1.6394,  0.9043,  1.8778,  1.8209,  1.5527, -0.1066,  1.1651,  2.7963],
        [ 2.3441,  2.0095,  1.8648, -1.0236, -1.1168,  1.6763,  1.8349, -1.2058]],
       device='cuda:0')
tensor([[ 1.6394,  0.9043,  1.8778,  1.8209,  1.5527, -0.1066,  1.1651,  2.7963],
        [ 2.3441,  2.0095,  1.8648, -1.0236, -1.1168,  1.6763,  1.8349, -1.2058]],
       dtype=torch.float64)


In [30]:
import numpy as np

In [31]:

a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)
"""
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
"""


[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


'\n[2. 2. 2. 2. 2.]\ntensor([2., 2., 2., 2., 2.], dtype=torch.float64)\n'

In [36]:
x,y

(tensor([[ 0.5352,  0.8761,  0.3468,  1.2977,  0.6653,  0.9737, -0.2880,  0.5690],
         [ 0.9584, -0.1313,  0.2494,  0.3314,  1.0418,  1.3972,  0.8570,  0.3844]],
        device='cuda:0'),
 tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]], device='cuda:0'))

0.0011506080627441406